### ISSUE TITLE
Bug: Parenthesis not punched

### ISSUE THREAD

**Issue by David-Fryd** [sahandbabali/Punch-Card-Generator#1]
If you try typing the input
`system.out.println("hello world");`
The characters including after the first parenthesis `("hello world");` are _**not**_ punched/recognized.

edit: seems to be an issue after typing any parenthesis. If the first character of the input is a parenthesis, none of the following text gets punched

**Comment by sahandbabali** [comment]
Thank you for bringing this issue to my attention! I'm pleased to inform you that the problem is solved, and all the following characters are now supported without any issues: "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ&-/:#@'="¢.<(+|!$*);¬ ,%_>?"
